title: "Joël's Blog"
remote_theme: jekyll/minima
minima:
  skin: dark
author: "Joël Fehr"
github_username: "jf-11"

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: jf-11-github-io
